services:
  - type: web
    name: pakistan-flood-story
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: MAPBOX_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
