# Generated by Django 5.2.17 on 2026-09-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('focus', models.CharField(blank=True, max_length=200)),
                ('answer', models.TextField()),
                ('provider', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'AI query',
                'verbose_name_plural': 'AI queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HazardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('hazard_type', models.CharField(choices=[('flood', 'Flood'), ('heatwave', 'Heatwave'), ('earthquake', 'Earthquake'), ('drought', 'Drought'), ('cyclone', 'Cyclone')], default='flood', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('injured', models.PositiveIntegerField(default=0)),
                ('people_affected', models.PositiveBigIntegerField(default=0)),
                ('people_displaced', models.PositiveBigIntegerField(default=0)),
                ('houses_damaged', models.PositiveIntegerField(default=0)),
                ('houses_destroyed', models.PositiveIntegerField(default=0)),
                ('livestock_lost', models.PositiveIntegerField(default=0)),
                ('roads_damaged_km', models.PositiveIntegerField(default=0)),
                ('bridges_damaged', models.PositiveIntegerField(default=0)),
                ('calamity_districts', models.PositiveIntegerField(default=0)),
                ('damage_usd_bn', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('loss_usd_bn', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('needs_usd_bn', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('pcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area_km2', models.FloatField(default=0)),
                ('geometry', models.JSONField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField()),
                ('used_for', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='floodmap.hazardevent')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date_label', models.CharField(max_length=40)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('description', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='floodmap.hazardevent')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('pcode', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area_km2', models.FloatField(default=0)),
                ('population', models.PositiveBigIntegerField(default=0, help_text='WorldPop 2020, as used by UNOSAT')),
                ('geometry', models.JSONField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='floodmap.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(default='mapbox://styles/mapbox/dark-v11', max_length=200)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('projection', models.CharField(default='globe', max_length=30)),
                ('show_markers', models.BooleanField(default=False)),
                ('marker_color', models.CharField(default='#ff5a4e', max_length=20)),
                ('inset', models.BooleanField(default=True, help_text='Globe inset minimap')),
                ('use_3d_terrain', models.BooleanField(default=True)),
                ('auto', models.BooleanField(default=False, help_text='Auto-advance chapters')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('byline', models.CharField(blank=True, max_length=200)),
                ('footer', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='floodmap.hazardevent')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.CreateModel(
            name='ExposureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('analysed_km2', models.FloatField(default=0)),
                ('flood_km2', models.FloatField(default=0)),
                ('exposed_population', models.PositiveBigIntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure', to='floodmap.district')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure', to='floodmap.hazardevent')),
            ],
            options={
                'ordering': ['period_start', 'period_end'],
                'indexes': [models.Index(fields=['event', 'period_start', 'period_end'], name='floodmap_ex_event_i_8f7c41_idx')],
                'unique_together': {('event', 'district', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ProvinceImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('injured', models.PositiveIntegerField(blank=True, null=True)),
                ('rainfall_anomaly_pct', models.IntegerField(blank=True, help_text='August rainfall vs normal (PMD)', null=True)),
                ('note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_impacts', to='floodmap.hazardevent')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='floodmap.province')),
            ],
            options={
                'ordering': ['-deaths'],
                'unique_together': {('event', 'province')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(help_text='Chapter id used in the page')),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full')], default='left', max_length=10)),
                ('hidden', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, help_text='URL or static path', max_length=300)),
                ('description', models.TextField(blank=True, help_text='HTML allowed')),
                ('center_lng', models.FloatField()),
                ('center_lat', models.FloatField()),
                ('zoom', models.FloatField(default=5)),
                ('pitch', models.FloatField(default=0)),
                ('bearing', models.FloatField(default=0)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('curve', models.FloatField(blank=True, null=True)),
                ('map_animation', models.CharField(choices=[('flyTo', 'flyTo'), ('easeTo', 'easeTo'), ('jumpTo', 'jumpTo')], default='flyTo', max_length=10)),
                ('rotate_animation', models.BooleanField(default=False)),
                ('callback', models.CharField(blank=True, help_text='Name of a JS function in story-callbacks.js', max_length=60)),
                ('on_chapter_enter', models.JSONField(blank=True, default=list, help_text='[{"layer": "id", "opacity": 1, "duration": 1000}]')),
                ('on_chapter_exit', models.JSONField(blank=True, default=list)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='floodmap.story')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('story', 'slug')},
            },
        ),
    ]
